version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgresbrain
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: nestjs123
      POSTGRES_DB: nestjs_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestjs -d nestjs_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: